---
title: "mpa_result_process"
output: html_document
date: "2023-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libaries
```{r}
library(tidyr)
library(janitor)
```

# process MPA results files to get identified proteins with >=2 unique peptide matches
```{r}
# read the list of unique peptides for the sample
unique_peptides <- read.csv("path_to_unique_peptides.csv", sep = "\t")

# read the list of inferred proteins for the sample
raw_data <- read.csv("path_to_identified_proteins.csv", sep = "\t")

# clean column names
unique_peptides <- unique_peptides %>% clean_names()

# change 2nd column name for both files to "gene_id" to keep consistency
colnames(unique_peptides)[2] <- "gene_id"
raw_data <- raw_data %>% clean_names()
colnames(raw_data)[2] <- "gene_id"
# remove row names
unique_peptides$x <- NULL 

# join unique peptides to raw mpa result (many-to-one)
joined <- left_join(raw_data, unique_peptides, by = "gene_id")

# get the list of proteins with >=2 unique peptide matches
protein_list <- joined %>%
filter(!is.na(peptide_sequence)) %>% # filter proteins without unique peptide matches
group_by(gene_id) %>%
summarize(n = n()) %>% # count number of unique peptide matches
filter(n >= 2) 

# filter raw protein file with >=2 unique peptide matches
data_filtered <- filter(raw_data, gene_id %in% protein_list$gene_id)

write.csv(data_filtered, "path_to_output_file.csv", row.names = F)
```


# example for loop for processing multiple files simultaneously (Optional)
```{r}
peptide_list <- list.files("/storage/jufengLab/jinlingrong/Project/proteomics/4_mpa_results/111_MAGs/unique_peptides_bySample", pattern = "*.csv")

uniPept_filtered <- data.frame()

for (file in peptide_list) {
  # read the list of unique peptides for the sample
  unique_peptides <- read.csv(paste0("/storage/jufengLab/jinlingrong/Project/proteomics/4_mpa_results/111_MAGs/unique_peptides_bySample", "/", file), sep = "\t")
  sample <- gsub(".csv", "", file)

  # original mpa inferred proteins for the sample
  raw_data <- read.csv(paste0("/storage/jufengLab/jinlingrong/Project/proteomics/4_mpa_results/111_MAGs/inferred_proteins_bySample", "/", file), sep = "\t")

  unique_peptides <- unique_peptides %>% clean_names()
  colnames(unique_peptides)[2] <- "gene_id"
  raw_data <- raw_data %>% clean_names()
  colnames(raw_data)[2] <- "gene_id"
  unique_peptides$x <- NULL

  # join unique peptides to raw mpa result (many-to-one)
  joined <- left_join(raw_data, unique_peptides, by = "gene_id")

  # filter
  protein_list <- joined %>%
  filter(!is.na(peptide_sequence)) %>% # filter proteins without unique peptide matches
  group_by(gene_id) %>%
  summarize(n = n()) %>% # count number of unique peptide matches
  filter(n >= 2) # filter proteins with >=2 unique peptide matches
  data_filtered <- filter(raw_data, gene_id %in% protein_list$gene_id)
  data_filtered$sample_id <- rep(sample, nrow(data_filtered))

  # add to the data frame
  uniPept_filtered <- rbind(uniPept_filtered, data_filtered) # 4311
}

write.csv(uniPept_filtered, paste0("/storage/jufengLab/jinlingrong/Project/proteomics/4_mpa_results/111_MAGs/MAGs_proteins_uniPept_fil_bySample.csv"), row.names = F)
```
